<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('calling_agents', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->index();$t->foreignId('chatbot_id')->nullable()->index();$t->string('name');$t->string('status')->default('active');$t->string('phone_number')->nullable()->index();$t->string('twilio_sid')->nullable();$t->string('elevenlabs_agent_id')->nullable();$t->string('elevenlabs_voice_id')->nullable();$t->text('first_message')->nullable();$t->longText('instructions')->nullable();$t->string('language',12)->default('en');$t->json('settings')->nullable();$t->timestamps();});
  Schema::create('calling_agent_phone_numbers', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->index();$t->foreignId('calling_agent_id')->nullable()->index();$t->string('number')->unique();$t->string('provider')->default('twilio');$t->string('provider_sid')->nullable();$t->json('capabilities')->nullable();$t->timestamps();});
  Schema::create('calling_agent_calls', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->index();$t->foreignId('calling_agent_id')->nullable()->index();$t->string('provider')->default('twilio');$t->string('call_sid')->nullable()->index();$t->string('direction')->nullable();$t->string('from')->nullable();$t->string('to')->nullable();$t->string('status')->default('queued');$t->integer('duration')->default(0);$t->decimal('price',10,4)->nullable();$t->string('recording_url')->nullable();$t->longText('summary')->nullable();$t->json('metadata')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('ended_at')->nullable();$t->timestamps();});
  Schema::create('calling_agent_active_calls', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->index();$t->foreignId('calling_agent_call_id')->nullable()->index();$t->string('call_sid')->unique();$t->string('from')->nullable();$t->string('to')->nullable();$t->string('state')->default('ringing');$t->json('context')->nullable();$t->timestamp('last_seen_at')->nullable();$t->timestamps();});
  Schema::create('calling_agent_messages', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->index();$t->foreignId('calling_agent_id')->nullable()->index();$t->string('provider')->default('twilio');$t->string('channel')->default('sms');$t->string('message_sid')->nullable()->index();$t->string('from')->nullable();$t->string('to')->nullable();$t->longText('body')->nullable();$t->string('direction')->nullable();$t->string('status')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('calling_agent_transcripts', function(Blueprint $t){$t->id();$t->foreignId('calling_agent_call_id')->index();$t->string('role')->default('user');$t->longText('text');$t->string('source')->nullable();$t->json('metadata')->nullable();$t->timestamps();});
  Schema::create('calling_agent_ivr_flows', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->index();$t->foreignId('calling_agent_id')->nullable()->index();$t->string('name');$t->string('trigger')->default('inbound_call');$t->json('definition');$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('calling_agent_usage_records', function(Blueprint $t){$t->id();$t->foreignId('tenant_id')->nullable()->index();$t->foreignId('calling_agent_id')->nullable()->index();$t->string('meter');$t->integer('quantity')->default(0);$t->string('unit')->default('second');$t->json('metadata')->nullable();$t->timestamps();});
 }
 public function down(): void { foreach(['calling_agent_usage_records','calling_agent_ivr_flows','calling_agent_transcripts','calling_agent_messages','calling_agent_active_calls','calling_agent_calls','calling_agent_phone_numbers','calling_agents'] as $table){Schema::dropIfExists($table);} }
};
